import { Params, ShaladarpanStudent } from './types'

export function getShaladarpanClassStudents(params: Params) {
  return Promise.resolve([
    {
      stdClass: '9',
      section: 'A',
      srNo: '2878',
      admissionDate: '08-07-2025',
      name: 'Aasif',
      lateStatus: '',
      fatherName: 'Umaradin',
      motherName: 'Madina Khatu',
      gender: 'M',
      dob: '01-07-2010',
      rollNo: '901',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'OBC',
      religion: 'Muslim',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: '',
      bhamashahCard: '',
      mobileNo: '9649403063',
      address: 'umaradin kalran ,phalodi,kalran,342301',
      annualParentalIncome: '0',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'Yes',
      ageOnPresent: '15',
      coCurricularActivity: 'None',
      distanceFromSchool: '5.5',
      marks: '78',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2901',
      admissionDate: '10-07-2025',
      name: 'AFSANA',
      lateStatus: '',
      fatherName: 'NEKU KHAN',
      motherName: 'NAIMU KHATU',
      gender: 'F',
      dob: '10-03-2012',
      rollNo: '902',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'OBC',
      religion: 'Muslim',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX2275',
      bhamashahCard: '',
      mobileNo: '9856658965',
      address: 'Hopardi,Phalodi,Hopardi,342301',
      annualParentalIncome: '0',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'Yes',
      ageOnPresent: '13',
      coCurricularActivity: 'None',
      distanceFromSchool: '1',
      marks: '54',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2342',
      admissionDate: '11-10-2021',
      name: 'Aniket Bhatia',
      lateStatus: '',
      fatherName: 'Ramesh Kumar',
      motherName: 'Geeta',
      gender: 'M',
      dob: '17-12-2012',
      rollNo: '903',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'SC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX4162',
      bhamashahCard: 'YDMUWUF',
      mobileNo: '9783600014',
      address: 'UTTARI MEGHWALON KI DHANI,PHALODI,HOPARDI,342301',
      annualParentalIncome: '150000',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '13',
      coCurricularActivity: 'None',
      distanceFromSchool: '6',
    },
  ])
  const url = new URL('/students/sheet', 'http://192.168.29.91:8081')
  Object.entries(params).forEach((v) => url.searchParams.set(...v))
  console.log(`fetching ${url}`)
  return fetch(url).then<ShaladarpanStudent[]>((res) => res.json())
}

export function addMarks(params: Params & { srNo: string; marks: string }) {
  const url = new URL('/students/sheet', 'http://192.168.29.91:8081')
  return fetch(url, { method: 'POST', body: JSON.stringify(params) })
}
