import { Params, ShaladarpanStudent } from '~/features/marks-entry/types'
import { initializeGoogle, sheets } from '~/lib/google-sheet'

export async function GET(request: Request) {
  // return Response.json(getMockData())

  const params = Object.fromEntries(new URL(request.url).searchParams) as Params
  await initializeGoogle()

  return Response.json(await getData(params))
  return getData(params).then(Response.json)
}

async function getData(params: Params) {
  const { data } = await sheets.values.batchGet({
    spreadsheetId: process.env.GOOGLE_SHEET_ID,
    ranges: ['sd!A2:AD', 'marks!A2:E'],
  })
  if (!data.valueRanges) return []
  const [{ values: studentsRows }, { values: marksRows }] = data.valueRanges
  if (!studentsRows) return []

  const marksMap = (marksRows ?? []).reduce((acc, [exam, subject, stdClass, srNo, mark]) => {
    if (stdClass === params.class && exam === params.exam && subject === params.subject) {
      acc.set(srNo, mark)
    }
    return acc
  }, new Map<string, string>())

  const students: ShaladarpanStudent[] = []

  for (const row of studentsRows) {
    if (row[0] !== params.class) continue
    const [
      stdClass,
      section,
      srNo,
      admissionDate,
      name,
      lateStatus,
      fatherName,
      motherName,
      gender,
      dob,
      rollNo,
      examRollNo,
      totalWorkingDays,
      totalAttendance,
      category,
      religion,
      previousYearMarks,
      nameOfSchool,
      schoolUdiseCode,
      aadharNo,
      bhamashahCard,
      mobileNo,
      address,
      annualParentalIncome,
      cwsnStatus,
      bplStatus,
      minorityStatus,
      ageOnPresent,
      coCurricularActivity,
      distanceFromSchool,
    ] = row

    students.push({
      stdClass,
      section,
      srNo,
      admissionDate,
      name,
      lateStatus,
      fatherName,
      motherName,
      gender,
      dob,
      rollNo,
      examRollNo,
      totalWorkingDays,
      totalAttendance,
      category,
      religion,
      previousYearMarks,
      nameOfSchool,
      schoolUdiseCode,
      aadharNo,
      bhamashahCard,
      mobileNo,
      address,
      annualParentalIncome,
      cwsnStatus,
      bplStatus,
      minorityStatus,
      ageOnPresent,
      coCurricularActivity,
      distanceFromSchool,
      marks: marksMap.get(srNo) || '',
    })
  }
  return students
}

export async function POST(request: Request) {
  const [{ exam, subject, class: stdClass, srNo, marks }] = await Promise.all([
    request.json() as Promise<Params & { srNo: string; marks: string }>,
    initializeGoogle(),
  ])
  await sheets.values.append({
    spreadsheetId: process.env.GOOGLE_SHEET_ID,
    range: 'marks',
    valueInputOption: 'RAW', // RAW or USER_ENTERED based on your data
    requestBody: {
      values: [[exam, subject, stdClass, srNo, marks]],
    },
  })
  return Response.json({ message: 'Success' })
}

function getMockData() {
  return [
    {
      stdClass: '9',
      section: 'A',
      srNo: '2878',
      admissionDate: '08-07-2025',
      name: 'Aasif',
      lateStatus: '',
      fatherName: 'Umaradin',
      motherName: 'Madina Khatu',
      gender: 'M',
      dob: '01-07-2010',
      rollNo: '901',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'OBC',
      religion: 'Muslim',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: '',
      bhamashahCard: '',
      mobileNo: '9649403063',
      address: 'umaradin kalran ,phalodi,kalran,342301',
      annualParentalIncome: '0',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'Yes',
      ageOnPresent: '15',
      coCurricularActivity: 'None',
      distanceFromSchool: '5.5',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2901',
      admissionDate: '10-07-2025',
      name: 'AFSANA',
      lateStatus: '',
      fatherName: 'NEKU KHAN',
      motherName: 'NAIMU KHATU',
      gender: 'F',
      dob: '10-03-2012',
      rollNo: '902',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'OBC',
      religion: 'Muslim',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX2275',
      bhamashahCard: '',
      mobileNo: '9856658965',
      address: 'Hopardi,Phalodi,Hopardi,342301',
      annualParentalIncome: '0',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'Yes',
      ageOnPresent: '13',
      coCurricularActivity: 'None',
      distanceFromSchool: '1',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2342',
      admissionDate: '11-10-2021',
      name: 'Aniket Bhatia',
      lateStatus: '',
      fatherName: 'Ramesh Kumar',
      motherName: 'Geeta',
      gender: 'M',
      dob: '17-12-2012',
      rollNo: '903',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'SC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX4162',
      bhamashahCard: 'YDMUWUF',
      mobileNo: '9783600014',
      address: 'UTTARI MEGHWALON KI DHANI,PHALODI,HOPARDI,342301',
      annualParentalIncome: '150000',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '13',
      coCurricularActivity: 'None',
      distanceFromSchool: '6',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '1663',
      admissionDate: '06-07-2017',
      name: 'ANIL',
      lateStatus: '',
      fatherName: 'NETARAM',
      motherName: 'SUNITA',
      gender: 'M',
      dob: '05-08-2009',
      rollNo: '905',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'SC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX2009',
      bhamashahCard: 'YMIYDIS',
      mobileNo: '8290299449',
      address: 'HOPARDI,PHALODI,HOPARDI,342301',
      annualParentalIncome: '30000',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '16',
      coCurricularActivity: 'None',
      distanceFromSchool: '2',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2785',
      admissionDate: '13-07-2024',
      name: 'Arun Kumar',
      lateStatus: '',
      fatherName: 'Surja Ram',
      motherName: 'Pushpa',
      gender: 'M',
      dob: '18-05-2012',
      rollNo: '906',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'ST',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX2353',
      bhamashahCard: '',
      mobileNo: '8619914325',
      address: 'uttari meghwalo ki dhaniya,phalodi,hopardi,342301',
      annualParentalIncome: '90000',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '13',
      coCurricularActivity: 'None',
      distanceFromSchool: '2',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2881',
      admissionDate: '10-07-2025',
      name: 'Ashish',
      lateStatus: '',
      fatherName: 'Poonamchand',
      motherName: 'Neni',
      gender: 'M',
      dob: '20-12-2011',
      rollNo: '907',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'OBC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: '',
      bhamashahCard: '',
      mobileNo: '9982176820',
      address: 'nayo ka bas ,phalodi,hopardi,342301',
      annualParentalIncome: '0',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '14',
      coCurricularActivity: 'None',
      distanceFromSchool: '6',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2862',
      admissionDate: '14-08-2024',
      name: 'Bablu',
      lateStatus: '',
      fatherName: 'Tejsingh',
      motherName: 'Tulsi',
      gender: 'M',
      dob: '14-03-2010',
      rollNo: '908',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'OBC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX1470',
      bhamashahCard: '',
      mobileNo: '6376769083',
      address: 'VILLAGE KHOHAR ,RAMGARH ,KHOHAR ,301025',
      annualParentalIncome: '60000',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '15',
      coCurricularActivity: 'None',
      distanceFromSchool: '1',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2482',
      admissionDate: '15-07-2022',
      name: 'CHANDRA PRAKASH',
      lateStatus: '',
      fatherName: 'BHOMA RAM',
      motherName: 'NAINA',
      gender: 'M',
      dob: '18-05-2012',
      rollNo: '909',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'SC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX0497',
      bhamashahCard: 'WDDDAMG',
      mobileNo: '9636111640',
      address: 'MEGHWALO KA BAS,PHALODI,HOPARADI,342301',
      annualParentalIncome: '50000',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '13',
      coCurricularActivity: 'None',
      distanceFromSchool: '0',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2779',
      admissionDate: '11-07-2024',
      name: 'Deepika',
      lateStatus: '',
      fatherName: 'Kishna Ram',
      motherName: 'Munni Devi',
      gender: 'F',
      dob: '15-06-2010',
      rollNo: '910',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'OBC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX5483',
      bhamashahCard: '',
      mobileNo: '9636503175',
      address: 'badla basani,tinwari,badla basani,342306',
      annualParentalIncome: '50000',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '15',
      coCurricularActivity: 'None',
      distanceFromSchool: '3',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2338',
      admissionDate: '04-10-2021',
      name: 'Devilal Suthar',
      lateStatus: '',
      fatherName: 'Ramchandra',
      motherName: 'Geeta',
      gender: 'M',
      dob: '01-01-2012',
      rollNo: '911',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'OBC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX4818',
      bhamashahCard: '',
      mobileNo: '9829319723',
      address: 'HOPARDI,PHALODI,HOPARDI,342301',
      annualParentalIncome: '150000',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '13',
      coCurricularActivity: 'None',
      distanceFromSchool: '6',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2948',
      admissionDate: '16-07-2025',
      name: 'Firoj',
      lateStatus: '',
      fatherName: 'Rafik',
      motherName: 'Savina',
      gender: 'M',
      dob: '03-07-2013',
      rollNo: '912',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'OBC',
      religion: 'Muslim',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: '',
      bhamashahCard: '',
      mobileNo: '9929245486',
      address: 'muslmano ki dhani,phalodi,hoprdi,342301',
      annualParentalIncome: '0',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'Yes',
      ageOnPresent: '12',
      coCurricularActivity: 'None',
      distanceFromSchool: '2',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2888',
      admissionDate: '10-07-2025',
      name: 'Gayad',
      lateStatus: '',
      fatherName: 'Swaroop Chand',
      motherName: 'Sua',
      gender: 'M',
      dob: '15-04-2010',
      rollNo: '913',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'OBC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX1549',
      bhamashahCard: '',
      mobileNo: '9829185469',
      address: 'NAEYO KA BASS,phalodi,TALIYA, HOPARDI,342301',
      annualParentalIncome: '0',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '15',
      coCurricularActivity: 'None',
      distanceFromSchool: '5.5',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2950',
      admissionDate: '21-07-2025',
      name: 'Gulabdin',
      lateStatus: '',
      fatherName: 'Mangala Khan',
      motherName: 'Animat',
      gender: 'M',
      dob: '01-01-2012',
      rollNo: '914',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'OBC',
      religion: 'Muslim',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: '',
      bhamashahCard: '',
      mobileNo: '9024715178',
      address: 'sindhiyo ki dhani,ranssir,kalau,342025',
      annualParentalIncome: '0',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'Yes',
      ageOnPresent: '13',
      coCurricularActivity: 'None',
      distanceFromSchool: '6',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2361',
      admissionDate: '10-11-2021',
      name: 'Hawa',
      lateStatus: '',
      fatherName: 'Omprakash',
      motherName: 'Indu',
      gender: 'F',
      dob: '15-11-2011',
      rollNo: '916',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'OBC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX7654',
      bhamashahCard: '',
      mobileNo: '8107979290',
      address: 'HOPARDI,PHALODI,HOPARDI,342301',
      annualParentalIncome: '0',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '14',
      coCurricularActivity: 'None',
      distanceFromSchool: '3',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2786',
      admissionDate: '13-07-2024',
      name: 'JEEWAN',
      lateStatus: '',
      fatherName: 'KHINV RAJ',
      motherName: 'BASANTI',
      gender: 'M',
      dob: '12-09-2009',
      rollNo: '917',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'SC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX9435',
      bhamashahCard: 'YACAWDO',
      mobileNo: '9826596321',
      address: 'CHACHA,POKARAN,CHACHA,34531',
      annualParentalIncome: '35000',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '16',
      coCurricularActivity: 'None',
      distanceFromSchool: '1',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '1661',
      admissionDate: '06-07-2017',
      name: 'JYOTI',
      lateStatus: '',
      fatherName: 'BAGSIRAM',
      motherName: 'MADHU DEVI',
      gender: 'F',
      dob: '06-08-2012',
      rollNo: '918',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'OBC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX1238',
      bhamashahCard: 'VKHTSRX',
      mobileNo: '9950076241',
      address: 'JAGIYON KA BAS,PHALODI,HOPARDI,342301',
      annualParentalIncome: '40000',
      cwsnStatus: 'N',
      bplStatus: 'Y',
      minorityStatus: 'No',
      ageOnPresent: '13',
      coCurricularActivity: 'None',
      distanceFromSchool: '1',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2644',
      admissionDate: '11-07-2023',
      name: 'KAILASH',
      lateStatus: '',
      fatherName: 'MAHENDRA RAM',
      motherName: 'BHANWARI',
      gender: 'M',
      dob: '03-02-2012',
      rollNo: '919',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'SC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX5602',
      bhamashahCard: 'YOWFDBC',
      mobileNo: '9602979464',
      address: 'Meghvalo ka bass,Bhopalgarh,Mandli charna,342603',
      annualParentalIncome: '100000',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '13',
      coCurricularActivity: 'None',
      distanceFromSchool: '1',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2712',
      admissionDate: '27-07-2023',
      name: 'Kailash',
      lateStatus: '',
      fatherName: 'Shiv Narayan',
      motherName: 'Meera Devi',
      gender: 'M',
      dob: '02-07-2012',
      rollNo: '920',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'GEN',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX1423',
      bhamashahCard: '',
      mobileNo: '9680516467',
      address: 'HOPARDI,HOPARDI,HOPARDI,342301',
      annualParentalIncome: '200000',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '13',
      coCurricularActivity: 'None',
      distanceFromSchool: '3',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2805',
      admissionDate: '16-07-2024',
      name: 'KANTA',
      lateStatus: '',
      fatherName: 'RAJUSINGH OAD',
      motherName: 'DARIYA KANWAR',
      gender: 'F',
      dob: '01-01-2008',
      rollNo: '922',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'OBC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX3618',
      bhamashahCard: 'VPWPCCT',
      mobileNo: '9950579808',
      address: 'BELDARO KA BASS,PHALODI,KUNDAL,342301',
      annualParentalIncome: '100000',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '17',
      coCurricularActivity: 'None',
      distanceFromSchool: '1',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2526',
      admissionDate: '21-07-2022',
      name: 'KHUSHBU',
      lateStatus: '',
      fatherName: 'PUKHRAJ',
      motherName: 'SUSHILA',
      gender: 'F',
      dob: '05-08-2008',
      rollNo: '923',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'OBC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX1768',
      bhamashahCard: '',
      mobileNo: '8290342925',
      address: 'BARSANADA,PHALODI,BARSANADA,342301',
      annualParentalIncome: '0',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '17',
      coCurricularActivity: 'None',
      distanceFromSchool: '1',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '1647',
      admissionDate: '04-07-2017',
      name: 'KIRAN',
      lateStatus: '',
      fatherName: 'CHENARAM',
      motherName: 'SONY',
      gender: 'F',
      dob: '21-07-2011',
      rollNo: '924',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'SC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX4440',
      bhamashahCard: 'VVHVVSV',
      mobileNo: '9772059174',
      address: 'MEGHWALO KI DHANI ,PHALODI,HOPARDI,342301',
      annualParentalIncome: '40000',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '14',
      coCurricularActivity: 'None',
      distanceFromSchool: '2',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2496',
      admissionDate: '16-07-2022',
      name: 'LALITA',
      lateStatus: '',
      fatherName: 'PURKHARAM',
      motherName: 'KESUDEVI',
      gender: 'F',
      dob: '01-01-2012',
      rollNo: '925',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'SC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX0953',
      bhamashahCard: 'vwntcgn',
      mobileNo: '8955211504',
      address: 'bhope ki dhani,phalodi,hopardi,342301',
      annualParentalIncome: '60000',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '13',
      coCurricularActivity: 'None',
      distanceFromSchool: '3',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2761',
      admissionDate: '05-07-2024',
      name: 'Mahendra',
      lateStatus: '',
      fatherName: 'Tauram',
      motherName: 'Sukhiya',
      gender: 'M',
      dob: '20-11-2011',
      rollNo: '926',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'SC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX5316',
      bhamashahCard: 'YMCYWDG',
      mobileNo: '6378627539',
      address: 'MEGHWALO KA BAS,PHALODI,HOPARDI,342301',
      annualParentalIncome: '50000',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '14',
      coCurricularActivity: 'None',
      distanceFromSchool: '5.5',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2463',
      admissionDate: '13-07-2022',
      name: 'Mahipal',
      lateStatus: '',
      fatherName: 'Padma Ram',
      motherName: 'Cheni Devi',
      gender: 'M',
      dob: '05-08-2012',
      rollNo: '927',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'SC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX2841',
      bhamashahCard: 'YPNWBZV',
      mobileNo: '6376200525',
      address: 'MEGHWALO KA BAS,PHALODI,HOPARADI,342301',
      annualParentalIncome: '50000',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '13',
      coCurricularActivity: 'None',
      distanceFromSchool: '1',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2497',
      admissionDate: '16-07-2022',
      name: 'MAMTA',
      lateStatus: '',
      fatherName: 'BHOMARAM',
      motherName: 'LACHAMI DEVI',
      gender: 'F',
      dob: '15-06-2012',
      rollNo: '928',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'SC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX1550',
      bhamashahCard: 'YWWBKEY',
      mobileNo: '9950455794',
      address: 'MEGHWALO KA BAS,PHALODI,HOPARDI,342301',
      annualParentalIncome: '50000',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '13',
      coCurricularActivity: 'None',
      distanceFromSchool: '1',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2883',
      admissionDate: '10-07-2025',
      name: 'Manjur Kha',
      lateStatus: '',
      fatherName: 'Islamdin',
      motherName: 'Jubeda Khatu',
      gender: 'M',
      dob: '28-05-2011',
      rollNo: '929',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'OBC',
      religion: 'Muslim',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: '',
      bhamashahCard: '',
      mobileNo: '9571521796',
      address: 'hopardi,phalodi,hopardi,342301',
      annualParentalIncome: '0',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'Yes',
      ageOnPresent: '14',
      coCurricularActivity: 'None',
      distanceFromSchool: '1',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2527',
      admissionDate: '21-07-2022',
      name: 'MANOJ',
      lateStatus: '',
      fatherName: 'PUKHRAJ',
      motherName: 'SUSHILA',
      gender: 'M',
      dob: '16-08-2010',
      rollNo: '930',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'OBC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX3914',
      bhamashahCard: '',
      mobileNo: '8290342925',
      address: 'BARSANADA,PHALODI,BARSANADA,342301',
      annualParentalIncome: '0',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '15',
      coCurricularActivity: 'None',
      distanceFromSchool: '1',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2643',
      admissionDate: '11-07-2023',
      name: 'Maya Goswami',
      lateStatus: '',
      fatherName: 'Om Puri',
      motherName: 'Magi Devi',
      gender: 'F',
      dob: '01-03-2013',
      rollNo: '931',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'OBC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX1900',
      bhamashahCard: '',
      mobileNo: '9784101317',
      address: 'D/O OM PURI GOSWAMI,PHALODI,HOPARDI,342301',
      annualParentalIncome: '80000',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '12',
      coCurricularActivity: 'None',
      distanceFromSchool: '1',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2852',
      admissionDate: '30-07-2024',
      name: 'Mehbub',
      lateStatus: '',
      fatherName: 'Gani Khan',
      motherName: 'Inayto',
      gender: 'M',
      dob: '03-04-2010',
      rollNo: '932',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'OBC',
      religion: 'Muslim',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: '',
      bhamashahCard: '',
      mobileNo: '7568471138',
      address: 'atte khan ki dhani,phalodi,hopardi,342301',
      annualParentalIncome: '50000',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'Yes',
      ageOnPresent: '15',
      coCurricularActivity: 'None',
      distanceFromSchool: '2',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2882',
      admissionDate: '10-07-2025',
      name: 'Mukesh',
      lateStatus: '',
      fatherName: 'Prakash',
      motherName: 'Munna',
      gender: 'M',
      dob: '30-07-2012',
      rollNo: '933',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'SC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: '',
      bhamashahCard: '',
      mobileNo: '9351163693',
      address: 'VILLAGE- DEDISARA,GRAM PANCHAYAT-BAPINI, BLOCK- PHALODI,JODHPUR,,342301',
      annualParentalIncome: '0',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '13',
      coCurricularActivity: 'None',
      distanceFromSchool: '1',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2966',
      admissionDate: '21-07-2025',
      name: 'MUMTAJ',
      lateStatus: '',
      fatherName: 'HABIB KHAN',
      motherName: 'PAPPU KHATU',
      gender: 'F',
      dob: '25-08-2013',
      rollNo: '934',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'OBC',
      religion: 'Muslim',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX8628',
      bhamashahCard: '',
      mobileNo: '7742172183',
      address: 'Hopardi,Phalodi,Hopardi,342301',
      annualParentalIncome: '0',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'Yes',
      ageOnPresent: '12',
      coCurricularActivity: 'None',
      distanceFromSchool: '1',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2969',
      admissionDate: '21-07-2025',
      name: 'MUSKAN',
      lateStatus: '',
      fatherName: 'HUSAIN KHAN',
      motherName: 'ASMA',
      gender: 'F',
      dob: '10-10-2012',
      rollNo: '935',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'OBC',
      religion: 'Muslim',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX',
      bhamashahCard: '',
      mobileNo: '9928757606',
      address: 'Hopardi,Phalodi,Hopardi,342301',
      annualParentalIncome: '0',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'Yes',
      ageOnPresent: '13',
      coCurricularActivity: 'None',
      distanceFromSchool: '1',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2343',
      admissionDate: '11-10-2021',
      name: 'Naitik Bhatia',
      lateStatus: '',
      fatherName: 'Ramesh Kumar',
      motherName: 'Geeta',
      gender: 'M',
      dob: '15-02-2012',
      rollNo: '936',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'SC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX3013',
      bhamashahCard: 'YDMUWUF',
      mobileNo: '9783600014',
      address: 'UTTARI MEGHWALON KI DHANI,PHALODI,HOPARDI,342301',
      annualParentalIncome: '150000',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '13',
      coCurricularActivity: 'None',
      distanceFromSchool: '5',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '1721',
      admissionDate: '10-07-2017',
      name: 'NARESH',
      lateStatus: '',
      fatherName: 'TOLARAM',
      motherName: 'DHANI DEVI',
      gender: 'M',
      dob: '01-01-2012',
      rollNo: '937',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'SC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX8115',
      bhamashahCard: '',
      mobileNo: '9828369244',
      address: 'BHOPE KI DHANI,PHALODI,HOPARDI,342301',
      annualParentalIncome: '50000',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '13',
      coCurricularActivity: 'None',
      distanceFromSchool: '2',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2465',
      admissionDate: '13-07-2022',
      name: 'Nemichand',
      lateStatus: '',
      fatherName: 'Leeladhar',
      motherName: 'Chhota Devi',
      gender: 'M',
      dob: '05-04-2011',
      rollNo: '938',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'SC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX6509',
      bhamashahCard: '',
      mobileNo: '8824197988',
      address: 'BHOPE KI DHANI,PHALODI,HOPARDI,342301',
      annualParentalIncome: '150000',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '14',
      coCurricularActivity: 'None',
      distanceFromSchool: '1',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '1717',
      admissionDate: '10-07-2017',
      name: 'PRAKASH',
      lateStatus: '',
      fatherName: 'CHETANRAM',
      motherName: 'GEETA',
      gender: 'M',
      dob: '22-02-2010',
      rollNo: '939',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'SC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX5098',
      bhamashahCard: '',
      mobileNo: '9166515008',
      address: 'bithri,hopardi,bithri,342301',
      annualParentalIncome: '70000',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '15',
      coCurricularActivity: 'None',
      distanceFromSchool: '6',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2806',
      admissionDate: '16-07-2024',
      name: 'PRAKASH OAD',
      lateStatus: '',
      fatherName: 'RAJU SINGH OAD',
      motherName: 'DARIYA KANWAR',
      gender: 'M',
      dob: '01-01-2011',
      rollNo: '940',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'OBC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX7919',
      bhamashahCard: '',
      mobileNo: '9950579808',
      address: 'BELDARO KA BASS,phalodi,KUNDAL,342301',
      annualParentalIncome: '100000',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '14',
      coCurricularActivity: 'None',
      distanceFromSchool: '1',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2711',
      admissionDate: '26-07-2023',
      name: 'Pramod',
      lateStatus: '',
      fatherName: 'Leeladhar',
      motherName: 'Sundar',
      gender: 'M',
      dob: '17-06-2012',
      rollNo: '941',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'GEN',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: '',
      bhamashahCard: '',
      mobileNo: '9119236980',
      address: 'DHAMTON KA BAS HOPARDI,HOPARDI,HOPARDI,342301',
      annualParentalIncome: '200000',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '13',
      coCurricularActivity: 'None',
      distanceFromSchool: '1',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2553',
      admissionDate: '30-07-2022',
      name: 'PREMA RAM',
      lateStatus: '',
      fatherName: 'BHURA RAM',
      motherName: 'NAKTU',
      gender: 'M',
      dob: '11-06-2011',
      rollNo: '942',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'SC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX9751',
      bhamashahCard: '',
      mobileNo: '9983082165',
      address: 'PABU CHANVRA,DECHU,KOLU PABUJI,342314',
      annualParentalIncome: '0',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '14',
      coCurricularActivity: 'None',
      distanceFromSchool: '1',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2378',
      admissionDate: '25-11-2021',
      name: 'Priyanka Sharma',
      lateStatus: '',
      fatherName: 'Dilip Kumar Sharma',
      motherName: 'Rekha',
      gender: 'F',
      dob: '11-02-2012',
      rollNo: '943',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'GEN',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX2397',
      bhamashahCard: '',
      mobileNo: '9799402527',
      address: 'DHAMTON KA BAS,PHALODI,HOPARDI,342301',
      annualParentalIncome: '96000',
      cwsnStatus: 'N',
      bplStatus: 'Y',
      minorityStatus: 'No',
      ageOnPresent: '13',
      coCurricularActivity: 'None',
      distanceFromSchool: '3',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2026',
      admissionDate: '19-07-2019',
      name: 'PURANMAL',
      lateStatus: '',
      fatherName: 'CHUTRARAM',
      motherName: 'NURI DEVI',
      gender: 'M',
      dob: '11-04-2012',
      rollNo: '944',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'SC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX0279',
      bhamashahCard: '',
      mobileNo: '9950057640',
      address: 'HOPARDI,PHALODI,HOPARDI,342301',
      annualParentalIncome: '55000',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '13',
      coCurricularActivity: 'None',
      distanceFromSchool: '4',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2972',
      admissionDate: '24-07-2025',
      name: 'Rahul',
      lateStatus: '',
      fatherName: 'Ashok Kumar',
      motherName: 'Fuli',
      gender: 'M',
      dob: '18-11-2012',
      rollNo: '945',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'SC',
      religion: '',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: '',
      bhamashahCard: '',
      mobileNo: '9602043845',
      address: '',
      annualParentalIncome: '',
      cwsnStatus: 'N',
      bplStatus: 'Y',
      minorityStatus: '',
      ageOnPresent: '13',
      coCurricularActivity: '',
      distanceFromSchool: '6',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2970',
      admissionDate: '21-07-2025',
      name: 'Rakesh',
      lateStatus: '',
      fatherName: 'Munna Ram',
      motherName: 'Indra',
      gender: 'M',
      dob: '23-07-2010',
      rollNo: '946',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'OBC',
      religion: '',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: '',
      bhamashahCard: '',
      mobileNo: '9521510312',
      address: '',
      annualParentalIncome: '',
      cwsnStatus: 'N',
      bplStatus: 'Y',
      minorityStatus: '',
      ageOnPresent: '15',
      coCurricularActivity: '',
      distanceFromSchool: '6',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2484',
      admissionDate: '15-07-2022',
      name: 'RAMESH',
      lateStatus: '',
      fatherName: 'JAGMALARAM',
      motherName: 'PAPPUDEVI',
      gender: 'M',
      dob: '16-03-2011',
      rollNo: '947',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'SC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX3301',
      bhamashahCard: '',
      mobileNo: '8769489515',
      address: 'bhopeji ki dhani,phalodi,hopardi,342301',
      annualParentalIncome: '0',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '14',
      coCurricularActivity: 'None',
      distanceFromSchool: '1',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2816',
      admissionDate: '19-07-2024',
      name: 'Ranveerpuri',
      lateStatus: '',
      fatherName: 'Punam Puri',
      motherName: 'Durga',
      gender: 'M',
      dob: '05-07-2012',
      rollNo: '948',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'OBC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: '',
      bhamashahCard: '',
      mobileNo: '9983659676',
      address: 'nai swamiyo ka bas,phalodi,hopardi ,342301',
      annualParentalIncome: '50000',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '13',
      coCurricularActivity: 'None',
      distanceFromSchool: '3',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2723',
      admissionDate: '08-08-2023',
      name: 'Ravikishan',
      lateStatus: '',
      fatherName: 'Bhomaram',
      motherName: 'Naina',
      gender: 'M',
      dob: '06-05-2010',
      rollNo: '949',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'SC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX4370',
      bhamashahCard: '',
      mobileNo: '9636111640',
      address: 'mhgwhlo dhaniya hoprdhi,phlodhi,hoprdhi,342301',
      annualParentalIncome: '200000',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '15',
      coCurricularActivity: 'None',
      distanceFromSchool: '3',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2911',
      admissionDate: '14-07-2025',
      name: 'RAVINA',
      lateStatus: '',
      fatherName: 'MANGILAL',
      motherName: 'SUA',
      gender: 'F',
      dob: '11-03-2012',
      rollNo: '950',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'SC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX1667',
      bhamashahCard: 'VKGKGGH',
      mobileNo: '9828189138',
      address: 'BAMNU,PHALODI,BAMNU,345021',
      annualParentalIncome: '90000',
      cwsnStatus: 'N',
      bplStatus: 'Y',
      minorityStatus: 'No',
      ageOnPresent: '13',
      coCurricularActivity: 'None',
      distanceFromSchool: '3',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '1986',
      admissionDate: '11-07-2019',
      name: 'RAVINA',
      lateStatus: '',
      fatherName: 'RATANLAL',
      motherName: 'SUSHILA',
      gender: 'F',
      dob: '09-07-2011',
      rollNo: '951',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'OBC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX5704',
      bhamashahCard: '',
      mobileNo: '9929354236',
      address: 'BAMNU,PHALODI,,345021',
      annualParentalIncome: '50000',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '14',
      coCurricularActivity: 'None',
      distanceFromSchool: '4',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '1662',
      admissionDate: '06-07-2017',
      name: 'ROSHNI',
      lateStatus: '',
      fatherName: 'NETARAM',
      motherName: 'SUNITA',
      gender: 'F',
      dob: '10-06-2008',
      rollNo: '952',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'SC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX4176',
      bhamashahCard: 'YMLYDIS',
      mobileNo: '8290299449',
      address: 'HOPARDI,PHALODI,HOPARDI,342301',
      annualParentalIncome: '100000',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '17',
      coCurricularActivity: 'None',
      distanceFromSchool: '2',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2828',
      admissionDate: '23-07-2024',
      name: 'Sandeep',
      lateStatus: 'Late',
      fatherName: 'Omkar Ram',
      motherName: 'Amu',
      gender: 'M',
      dob: '10-08-2011',
      rollNo: '953',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'SC',
      religion: '',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX3756',
      bhamashahCard: '',
      mobileNo: '6375174056',
      address: 'MEGHWALO KI DHANI,PHALODI,HOPARDI,342301',
      annualParentalIncome: '0',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: '',
      ageOnPresent: '14',
      coCurricularActivity: 'None',
      distanceFromSchool: '1',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2804',
      admissionDate: '16-07-2024',
      name: 'SANTOSH',
      lateStatus: '',
      fatherName: 'RAJUSINGH OAD',
      motherName: 'DARIYA KANWAR',
      gender: 'F',
      dob: '01-01-2006',
      rollNo: '954',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'OBC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX4001',
      bhamashahCard: 'VPWPCCT',
      mobileNo: '9950579808',
      address: 'BARSANADA,PHALODI,BARSANADA,342301',
      annualParentalIncome: '100000',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '19',
      coCurricularActivity: 'None',
      distanceFromSchool: '1',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2360',
      admissionDate: '10-11-2021',
      name: 'Santu',
      lateStatus: '',
      fatherName: 'Shiv Lal',
      motherName: 'Narba',
      gender: 'F',
      dob: '04-10-2011',
      rollNo: '955',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'OBC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX0053',
      bhamashahCard: '',
      mobileNo: '8107979290',
      address: 'HOPARDI,PHALODI,HOPARDI,342301',
      annualParentalIncome: '50000',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '14',
      coCurricularActivity: 'None',
      distanceFromSchool: '3',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2935',
      admissionDate: '15-07-2025',
      name: 'Seema',
      lateStatus: '',
      fatherName: 'Mangilal',
      motherName: 'Nainu',
      gender: 'F',
      dob: '11-02-2011',
      rollNo: '957',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'OBC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: '',
      bhamashahCard: '',
      mobileNo: '6375402005',
      address: 'mangi lal ganv ,phalodi,taliya dhadhu,345021',
      annualParentalIncome: '80000',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '14',
      coCurricularActivity: 'None',
      distanceFromSchool: '6',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2977',
      admissionDate: '24-07-2025',
      name: 'Seema',
      lateStatus: '',
      fatherName: 'Jagdish',
      motherName: 'Kamla',
      gender: 'F',
      dob: '28-12-2012',
      rollNo: '956',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'SC',
      religion: '',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: '',
      bhamashahCard: '',
      mobileNo: '6350393437',
      address: '',
      annualParentalIncome: '',
      cwsnStatus: 'N',
      bplStatus: 'Y',
      minorityStatus: '',
      ageOnPresent: '13',
      coCurricularActivity: '',
      distanceFromSchool: '6',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2455',
      admissionDate: '13-07-2022',
      name: 'Sunil',
      lateStatus: '',
      fatherName: 'Pemaram',
      motherName: 'Shivli',
      gender: 'M',
      dob: '01-01-2011',
      rollNo: '958',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'OBC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX1871',
      bhamashahCard: '',
      mobileNo: '9829415451',
      address: 'BHAKHARIYO KI DHANI,PIPAR CITY,SINDHIPURA,342601',
      annualParentalIncome: '0',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '14',
      coCurricularActivity: 'None',
      distanceFromSchool: '3',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2704',
      admissionDate: '22-07-2023',
      name: 'Sunil',
      lateStatus: '',
      fatherName: 'Tolaram',
      motherName: 'Pappu Devi',
      gender: 'M',
      dob: '05-07-2010',
      rollNo: '959',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'SC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX5985',
      bhamashahCard: '',
      mobileNo: '9950088726',
      address: 'MEGHWALO KA BASS,PHALODI,MOKHERI,342301',
      annualParentalIncome: '130000',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '15',
      coCurricularActivity: 'None',
      distanceFromSchool: '6',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '1612',
      admissionDate: '27-06-2017',
      name: 'TARUNA',
      lateStatus: '',
      fatherName: 'SHAITAN PURI',
      motherName: 'BABLI',
      gender: 'F',
      dob: '01-03-2013',
      rollNo: '961',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'OBC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX3338',
      bhamashahCard: 'vhhoojh',
      mobileNo: '7568209691',
      address: 'nayon ka vas,phalodi,hopardi,342301',
      annualParentalIncome: '60000',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '12',
      coCurricularActivity: 'None',
      distanceFromSchool: '4',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2873',
      admissionDate: '08-07-2025',
      name: 'Tofik',
      lateStatus: '',
      fatherName: 'Saradin kha',
      motherName: 'Jubeda khatu',
      gender: 'M',
      dob: '07-02-2010',
      rollNo: '962',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'OBC',
      religion: 'Muslim',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX3691',
      bhamashahCard: '',
      mobileNo: '9865896589',
      address: 'Hopardi,Phalodi,Hopardi,342301',
      annualParentalIncome: '0',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'Yes',
      ageOnPresent: '15',
      coCurricularActivity: 'None',
      distanceFromSchool: '1',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2434',
      admissionDate: '11-07-2022',
      name: 'URAMILA',
      lateStatus: '',
      fatherName: 'KISHANLAL',
      motherName: 'NIRMLA DEVI',
      gender: 'F',
      dob: '14-07-2012',
      rollNo: '963',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'SC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX4122',
      bhamashahCard: 'YQMOCOC',
      mobileNo: '8890921273',
      address: 'MEGHWALO KA BAS,PHALODI,HOPARDI,342301',
      annualParentalIncome: '50000',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '13',
      coCurricularActivity: 'None',
      distanceFromSchool: '1',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2695',
      admissionDate: '18-07-2023',
      name: 'Vishal',
      lateStatus: '',
      fatherName: 'Pukhraj',
      motherName: 'Dhai',
      gender: 'M',
      dob: '01-01-2010',
      rollNo: '964',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'SC',
      religion: 'Hindu',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: 'XXXX7868',
      bhamashahCard: '',
      mobileNo: '9636165492',
      address: 'MEGHWALO KA BAS,PHALODI,MOKHERI,342301',
      annualParentalIncome: '90000',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'No',
      ageOnPresent: '15',
      coCurricularActivity: 'None',
      distanceFromSchool: '5',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2947',
      admissionDate: '16-07-2025',
      name: 'Yunish Kha',
      lateStatus: '',
      fatherName: 'Bahadur Khan',
      motherName: 'Rasida',
      gender: 'M',
      dob: '22-09-2011',
      rollNo: '965',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'OBC',
      religion: 'Muslim',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: '',
      bhamashahCard: '',
      mobileNo: '9784101351',
      address: 'musalmano ki dhani,phalodi,hopardi,342301',
      annualParentalIncome: '0',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'Yes',
      ageOnPresent: '14',
      coCurricularActivity: 'None',
      distanceFromSchool: '5',
    },
    {
      stdClass: '9',
      section: 'A',
      srNo: '2963',
      admissionDate: '21-07-2025',
      name: 'Yunsh',
      lateStatus: '',
      fatherName: 'Iliyas',
      motherName: 'Habibo',
      gender: 'M',
      dob: '01-01-2011',
      rollNo: '966',
      examRollNo: '',
      totalWorkingDays: '',
      totalAttendance: '',
      category: 'OBC',
      religion: 'Muslim',
      previousYearMarks: '',
      nameOfSchool: 'GOVT. SENIOR SECONDARY SCHOOL HOPARDI (220180)',
      schoolUdiseCode: '8150207301',
      aadharNo: '',
      bhamashahCard: '',
      mobileNo: '9828565978',
      address: 'bijalighar ka pass,phalodi,kalra,342301',
      annualParentalIncome: '96000',
      cwsnStatus: 'N',
      bplStatus: 'N',
      minorityStatus: 'Yes',
      ageOnPresent: '14',
      coCurricularActivity: 'None',
      distanceFromSchool: '5',
    },
  ]
}
