name: Release

on:
  push:
    branches: [main]

jobs:
  create-release:
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: |
            - args: [--frozen-lockfile]
      - uses: actions/setup-node@v4
        with:
          node-version: '>=20.11'
          cache: 'pnpm'

      # Prepare for github release with the zipped artifact
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm run release
